version: '3.3'
services:
   yacd:
        image: ghcr.io/haishanh/yacd:master
        restart: always
        ports:
          - "880:80"
        # command: ["-p", "801"]
        #network_mode: host
        # networks:
        #   macnet:
        #     ipv4_address: "192.168.88.148"

# networks:
#   macnet:
#     external: true
#     name: macnet