version: "3.9"
services:
  windows:
    image: dockurr/windows:latest
    container_name: windows
    stop_grace_period: 2m
    restart: unless-stopped
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_SIZE: "256G"
      MANUAL: "N"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8007:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /docker/windows/storage:/storage