# 写一个nginx,docker-compose的文件。
version: '3.8'
services:
    web:
      image: nginx
      restart: always
      ports:
        - "80:80"
      volumes:
        - //home/lilin/.nginx/conf.d:/etc/nginx/conf.d
        - /home/lilin/.nginx/html:/usr/share/nginx/html
        - /home/lilin/.nginx/logs:/var/log/nginx
      command: bash -c "nginx -g 'daemon off;'"
    db:
      image: mysql:5.7
      restart: always
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=mydatabase
        - MYSQL_USER=myuser
        - MYSQL_PASSWORD=mypassword
      volumes:
        - /home/lilin/.mysql/data:/var/lib/mysql
        - /home/lilin/.mysql/logs:/var/log/mysql
        - /home/lilin/.mysql/conf.d:/etc/mysql/conf.d
    redis:
      image: redis:alpine
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - /home/lilin/.redis/data:/data
        - /home/lilin/.redis/conf/redis.conf:/usr/local/etc/redis/redis.conf


 
