#version: '3.8'
x-extra-hosts: &extra_hosts
  extra_hosts:
    - ${EXTRA_HOSTS}

x-common-volumes: &common-volumes
  - ${MPT_DIR}.MoneyPrinterTurbo:/MoneyPrinterTurbo

x-common-proxy: &common-proxy
  HTTP_PROXY: "http://${PORXY_HOST}:${PROXY_PORT}"
  HTTPS_PROXY: "http://${PORXY_HOST}:${PROXY_PORT}"
  NO_PROXY: localhost,127.0.0.1

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile-MonePrinterTurbo
      args:
        <<: *common-proxy
    environment:
      <<: *common-proxy
    container_name: "moneyprinterturbo-webui"
    ports:
      - "8501:8501"
    <<: *extra_hosts
    command: [
      "streamlit", "run", "./webui/Main.py",
      "--browser.serverAddress=127.0.0.1",
      "--server.enableCORS=True",
      "--browser.gatherUsageStats=False"
    ]
    volumes: *common-volumes
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile-MonePrinterTurbo
      args:
        <<: *common-proxy
    environment:
      <<: *common-proxy
    container_name: "moneyprinterturbo-api"
    ports:
      - "8080:8080"
    <<: *extra_hosts
    command: [ "python3", "main.py" ]
    volumes: *common-volumes
    restart: always
