name: n8n
services:
    n8n:
        volumes:
            - ${N8N_DIR}/.docker/n8n/pki:/opt/custom-certificates
        container_name: n8n
        ports:
            - 5678:5678
        image: docker.n8n.io/n8nio/n8n
        environment:
            - N8N_RUNNERS_ENABLED=true
            - N8N_SECURE_COOKIE=false
            - N8N_BASIC_AUTH_ACTIVE=true
            - N8N_BASIC_AUTH_USER=admin
            - N8N_BASIC_AUTH_PASSWORD=123456
            - HTTP_PROXY=${HTTP_PROXY}
            - HTTPS_PROXY=${HTTPS_PROXY}
            - N8N_HOST=${N8N_HOST}
            - N8N_PORT=${N8N_PORT}
            - N8N_PROTOCOL=${N8N_PROTOCOL}
            - WEBHOOK_URL=${WEBHOOK_URL}
        restart: unless-stopped

